api: vulkan
version: 1.4

extensions:
  - VK_KHR_surface
  - VK_KHR_swapchain
  - VK_KHR_xlib_surface
  - VK_KHR_xcb_surface
  - VK_KHR_wayland_surface
  - VK_KHR_win32_surface
  - VK_EXT_debug_utils
  - VK_EXT_validation_features

platforms:
  - xlib
  - xcb
  - wayland
  - win32
