version: '3'

tasks:
  generate:
    desc: Generate the go bindings
    cmds:
      - go run ./gen/...
      - go fmt ./pkg/raw/...

  test:
    desc: Test basic vulkan function
    deps: [ 'generate' ]
    cmds:
      - go run ./test/test.go