version: '3'

tasks:
  generate:
    desc: Generate the go bindings
    cmds:
      - go run ./cmd/gen/main.go
      
  test:
    desc: Test basic vulkan function
    deps: [ 'generate' ]
    cmds:
      - glslc -o ./test/test.spv ./test/test.comp
      - go run ./test/test.go
      