// Code generated by vulkan-go generator. DO NOT EDIT.

package vk

import (
	"sync"
	"unsafe"

	"github.com/go-webgpu/goffi/ffi"
)

type allocationCallbacksCallbacks struct {
	Allocation         AllocationFunction
	Reallocation       ReallocationFunction
	Free               FreeFunction
	InternalAllocation InternalAllocationNotification
	InternalFree       InternalFreeNotification
	UserData           unsafe.Pointer
}

var allocationCallbacksCallbackRegistry sync.Map

var _trampoline_AllocationCallbacks_Allocation uintptr = ffi.NewCallback(func(p0 unsafe.Pointer, p1 uintptr, p2 uintptr, p3 uint32) unsafe.Pointer {
	v, ok := allocationCallbacksCallbackRegistry.Load(p3)
	if !ok {
		return nil
	}
	holder := v.(*allocationCallbacksCallbacks)
	if holder.Allocation == nil {
		return nil
	}
	result := holder.Allocation(p0, uintptr(p1), uintptr(p2), SystemAllocationScope(p3))
	return result
})

var _trampoline_AllocationCallbacks_Reallocation uintptr = ffi.NewCallback(func(p0 unsafe.Pointer, p1 unsafe.Pointer, p2 uintptr, p3 uintptr, p4 uint32) unsafe.Pointer {
	v, ok := allocationCallbacksCallbackRegistry.Load(p4)
	if !ok {
		return nil
	}
	holder := v.(*allocationCallbacksCallbacks)
	if holder.Reallocation == nil {
		return nil
	}
	result := holder.Reallocation(p0, p1, uintptr(p2), uintptr(p3), SystemAllocationScope(p4))
	return result
})

var _trampoline_AllocationCallbacks_Free uintptr = ffi.NewCallback(func(p0 unsafe.Pointer, p1 unsafe.Pointer) {
	v, ok := allocationCallbacksCallbackRegistry.Load(p1)
	if !ok {
		return
	}
	holder := v.(*allocationCallbacksCallbacks)
	if holder.Free == nil {
		return
	}
	holder.Free(p0, p1)
})

var _trampoline_AllocationCallbacks_InternalAllocation uintptr = ffi.NewCallback(func(p0 unsafe.Pointer, p1 uintptr, p2 uint32, p3 uint32) {
	v, ok := allocationCallbacksCallbackRegistry.Load(p3)
	if !ok {
		return
	}
	holder := v.(*allocationCallbacksCallbacks)
	if holder.InternalAllocation == nil {
		return
	}
	holder.InternalAllocation(p0, uintptr(p1), InternalAllocationType(p2), SystemAllocationScope(p3))
})

var _trampoline_AllocationCallbacks_InternalFree uintptr = ffi.NewCallback(func(p0 unsafe.Pointer, p1 uintptr, p2 uint32, p3 uint32) {
	v, ok := allocationCallbacksCallbackRegistry.Load(p3)
	if !ok {
		return
	}
	holder := v.(*allocationCallbacksCallbacks)
	if holder.InternalFree == nil {
		return
	}
	holder.InternalFree(p0, uintptr(p1), InternalAllocationType(p2), SystemAllocationScope(p3))
})

type debugUtilsMessengerCreateInfoEXTCallbacks struct {
	UserCallback DebugUtilsMessengerCallbackEXT
	UserData     unsafe.Pointer
}

var debugUtilsMessengerCreateInfoEXTCallbackRegistry sync.Map

var _trampoline_DebugUtilsMessengerCreateInfoEXT_UserCallback uintptr = ffi.NewCallback(func(p0 uint32, p1 uint32, p2 unsafe.Pointer, p3 unsafe.Pointer) uint32 {
	v, ok := debugUtilsMessengerCreateInfoEXTCallbackRegistry.Load(p3)
	if !ok {
		return uint32(0)
	}
	holder := v.(*debugUtilsMessengerCreateInfoEXTCallbacks)
	if holder.UserCallback == nil {
		return uint32(0)
	}
	result := holder.UserCallback(DebugUtilsMessageSeverityFlagBitsEXT(p0), DebugUtilsMessageTypeFlagsEXT(p1), func() *DebugUtilsMessengerCallbackDataEXT {
		var _go_p2 DebugUtilsMessengerCallbackDataEXT
		_go_p2.fromC((*cVkDebugUtilsMessengerCallbackDataEXT)(p2))
		return &_go_p2
	}(), p3)
	if result {
		return uint32(1)
	}
	return uint32(0)
})
