// Code generated by vulkan-go generator. DO NOT EDIT.

//go:build windows

package vk

import (
	"unsafe"

	"github.com/go-webgpu/goffi/ffi"
)

type cVkWin32SurfaceCreateInfoKHR struct {
	sType     int32
	pNext     unsafe.Pointer
	flags     uint32
	hinstance unsafe.Pointer
	hwnd      unsafe.Pointer
}

type Win32SurfaceCreateInfoKHR struct {
	Next      Structure
	Flags     Win32SurfaceCreateFlagsKHR
	Hinstance unsafe.Pointer
	Hwnd      unsafe.Pointer
}

func (s *Win32SurfaceCreateInfoKHR) GetType() StructureType {
	return StructureTypeWin32SurfaceCreateInfoKHR
}

func (s *Win32SurfaceCreateInfoKHR) toC() (unsafe.Pointer, func()) {
	cancels := make([]func(), 0)
	p := new(cVkWin32SurfaceCreateInfoKHR)
	p.sType = int32(s.GetType())
	if s.Next != nil {
		nextPtr, nextCancel := s.Next.toC()
		cancels = append(cancels, nextCancel)
		p.pNext = nextPtr
	}
	val0 := uint32(s.Flags)
	p.flags = val0
	ext1 := unsafe.Pointer(s.Hinstance)
	p.hinstance = ext1
	ext2 := unsafe.Pointer(s.Hwnd)
	p.hwnd = ext2
	return unsafe.Pointer(p), func() {
		for _, cancel := range cancels {
			cancel()
		}
	}
}

func (s *Win32SurfaceCreateInfoKHR) fromC(p *cVkWin32SurfaceCreateInfoKHR) {
	s.Flags = Win32SurfaceCreateFlagsKHR(p.flags)
	s.Hinstance = unsafe.Pointer(p.hinstance)
	s.Hwnd = unsafe.Pointer(p.hwnd)
}

func (h Instance) CreateWin32SurfaceKHR(
	CreateInfo *Win32SurfaceCreateInfoKHR,
	Allocator *AllocationCallbacks,
) (*SurfaceKHR, error) {
	cancels := make([]func(), 0)
	defer func() {
		for _, c := range cancels {
			c()
		}
	}()

	_recv := h.handle
	var ptr0 unsafe.Pointer
	if CreateInfo != nil {
		val1, cancel2 := CreateInfo.toC()
		cancels = append(cancels, cancel2)
		ptr0 = val1
	}
	var ptr3 unsafe.Pointer
	if Allocator != nil {
		val4, cancel5 := Allocator.toC()
		cancels = append(cancels, cancel5)
		ptr3 = val4
	}
	var surfaceOut unsafe.Pointer
	_surfaceOutSlot := unsafe.Pointer(&surfaceOut)
	var _ret int32
	ffi.CallFunction(&_cif_vkCreateWin32SurfaceKHR, h.table.vkCreateWin32SurfaceKHR, unsafe.Pointer(&_ret), []unsafe.Pointer{
		unsafe.Pointer(&_recv),
		unsafe.Pointer(&ptr0),
		unsafe.Pointer(&ptr3),
		unsafe.Pointer(&_surfaceOutSlot),
	})
	if _ret != int32(Success) {
		return nil, Result(_ret)
	}
	h6 := &SurfaceKHR{handle: unsafe.Pointer(surfaceOut)}
	return h6, nil
}

func (h PhysicalDevice) GetWin32PresentationSupportKHR(
	queueFamilyIndex uint32,
) bool {
	cancels := make([]func(), 0)
	defer func() {
		for _, c := range cancels {
			c()
		}
	}()

	_recv := h.handle
	val0 := uint32(queueFamilyIndex)
	var _ret uint32
	ffi.CallFunction(&_cif_vkGetPhysicalDeviceWin32PresentationSupportKHR, h.table.vkGetPhysicalDeviceWin32PresentationSupportKHR, unsafe.Pointer(&_ret), []unsafe.Pointer{
		unsafe.Pointer(&_recv),
		unsafe.Pointer(&val0),
	})
	val1 := _ret != 0
	return val1
}
