package main

import (
	"encoding/xml"
	"io"
	"os"
	"strings"
)

const header = `
	// This file has been generated by
	// go-Vulkan please do not edit.

	package vulkan

	/*
		#cgo CFLAGS: -I./mod/Vulkan-Headers/include
		#cgo LDFLAGS: -LVulkanSDK/lib -lvulkan

		#define VK_USE_PLATFORM_ANDROID_KHR 1
		#define VK_USE_PLATFORM_FUCHSIA 1
		#define VK_USE_PLATFORM_IOS_MVK 1
		#define VK_USE_PLATFORM_MACOS_MVK 1
		#define VK_USE_PLATFORM_METAL_EXT 1
		#define VK_USE_PLATFORM_VI_NN 1
		#define VK_USE_PLATFORM_WAYLAND_KHR 1
		#define VK_USE_PLATFORM_WIN32_KHR 1
		#define VK_USE_PLATFORM_XCB_KHR 1
		#define VK_USE_PLATFORM_XLIB_KHR 1
		#define VK_USE_PLATFORM_DIRECTFB_EXT 1
		#define VK_USE_PLATFORM_XLIB_XRANDR_EXT 1
		#define VK_USE_PLATFORM_GGP 1
		#define VK_USE_PLATFORM_SCREEN_QNX 1
		#define VK_USE_PLATFORM_SCI 1
		#define VK_ENABLE_BETA_EXTENSIONS 1
		#define VK_USE_PLATFORM_OHOS 1

		#include <vulkan/vulkan.h>
	*/
	import "C"

`

type Type struct {
	Category string `xml:"category,attr"`
	NameAttr string `xml:"name,attr"` // for attribute-style
	NameElem string `xml:"name"`      // for element-style
	InnerXML string `xml:",innerxml"` // full raw body
}

type VkParser struct {
	structures strings.Builder
	functions  strings.Builder
	enums      strings.Builder
}

func (p *VkParser) Process(file *os.File) error {
	decoder := xml.NewDecoder(file)

	p.structures.WriteString(header)
	p.functions.WriteString(header)
	p.enums.WriteString(header)

	p.functions.WriteString("\nimport \"fmt\"\n")

	for {
		tok, err := decoder.Token()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}

		se, ok := tok.(xml.StartElement)
		if !ok {
			continue
		}

		switch se.Name.Local {
		case "type":
			err := p.parseType(decoder, se)
			if err != nil {
				return err
			}

		case "enums":
			var enum Enumeration
			if err := decoder.DecodeElement(&enum, &se); err != nil {
				return err
			}

			err := p.parseEnum(enum)
			if err != nil {
				return err
			}
		case "command":
			var cmd Command
			if err := decoder.DecodeElement(&cmd, &se); err != nil {
				return err
			}

			p.parseCommand(cmd)
		}

	}
}

func (p *VkParser) parseType(decoder *xml.Decoder, se xml.StartElement) error {
	var t Type
	if err := decoder.DecodeElement(&t, &se); err != nil {
		return err
	}

	if t.Category == "" {
		return nil
	}

	var name string
	if t.NameAttr != "" {
		name = t.NameAttr
	} else {
		name = t.NameElem
	}

	switch t.Category {
	case "struct":
		err := p.parseStruct(name, []byte(t.InnerXML))
		if err != nil {
			return err
		}
	default:
		//fmt.Println("Unhandled type:", t.Category, name)
	}

	return nil
}

func (p *VkParser) Save() error {
	err := os.WriteFile("./pkg/raw/functions.go", []byte(p.functions.String()), 0644)
	if err != nil {
		return err
	}

	err = os.WriteFile("./pkg/raw/structures.go", []byte(p.structures.String()), 0644)
	if err != nil {
		return err
	}

	err = os.WriteFile("./pkg/raw/enums.go", []byte(p.enums.String()), 0644)
	if err != nil {
		return err
	}

	return nil
}
