package generator

// APIConstant is a single entry from the Vulkan API constants block.
type APIConstant struct {
	GoName string
	Value  string // already translated to valid Go syntax
	Type   string // "uint32", "uint64", "float32", "float64", or "" (untyped int)
}

// Registry is the full parsed Vulkan registry. It contains Features and
// Extensions for use by Filter to build a ReducedRegistry.
type Registry struct {
	Enums        map[string]*Enum
	Bitmasks     map[string]*Bitmask
	EnumAliases  map[string]*EnumAlias
	Structs      map[string]*Structured
	Handles      map[string]*GoHandle
	Commands     map[string]*GoCommand
	Features     map[string]*Feature
	Extensions   map[string]*Extension
	FuncPointers map[string]*GoFuncPointer
	STypes       map[string]string
	APIConstants []APIConstant
	Platforms    map[string]string // platform name → protect macro (e.g. "xlib" → "VK_USE_PLATFORM_XLIB_KHR")
}

// ReducedRegistry is the filtered subset of the Registry that is ready for
// code generation. It does not include Features or Extensions.
type ReducedRegistry struct {
	Enums        map[string]*Enum
	Bitmasks     map[string]*Bitmask
	EnumAliases  map[string]*EnumAlias
	Structs      map[string]*Structured
	Handles      map[string]*GoHandle
	Commands     map[string]*GoCommand
	FuncPointers map[string]*GoFuncPointer
	STypes       map[string]string
	APIConstants []APIConstant
	Platforms    map[string]string
}

// PlatformBuildTag maps a Vulkan platform name to a Go build tag.
var PlatformBuildTag = map[string]string{
	"xlib":    "linux",
	"xcb":     "linux",
	"wayland": "linux",
	"win32":   "windows",
	"metal":   "darwin",
	"macos":   "darwin",
	"android": "android",
}

// PlatformFile represents a generated Go source file for a specific platform.
type PlatformFile struct {
	BuildTag string // e.g. "linux"
	Platform string // e.g. "xlib"
	Content  string
}

// AddEnumElement adds an enum element to the named enum in the Registry.
func (r *Registry) AddEnumElement(extends string, el *EnumElement) {
	if e, ok := r.Enums[extends]; ok {
		el.Parent = e
		e.Elements = append(e.Elements, el)
	}
}

// ---------------------------------------------------------------------------
// Generated file headers and preamble constants
// ---------------------------------------------------------------------------

const generatedHeader = "// Code generated by vulkan-go generator. DO NOT EDIT.\n\n"

// goffiHeader is the import block emitted at the top of the main generated file.
const goffiHeader = `import (
	"fmt"
	"runtime"
	"unsafe"

	"github.com/go-webgpu/goffi/ffi"
	"github.com/go-webgpu/goffi/types"
)
`

// goffiPlatformHeader is the import block emitted at the top of platform-specific files.
const goffiPlatformHeader = `import (
	"unsafe"

	"github.com/go-webgpu/goffi/ffi"
)
`

// goffiCallbacksHeader is the import block emitted at the top of the callbacks file.
const goffiCallbacksHeader = `import (
	"sync"
	"unsafe"

	"github.com/go-webgpu/goffi/ffi"
)
`

// runtimeHelpers is emitted into the main generated file after the import block.
// It provides the Structure interface, _cGoString helper, and surface utilities.
// Initialize/LoadInstance/LoadDevice are generated separately by output.go.
const runtimeHelpers = `
// Structure is the interface implemented by all Vulkan structs that carry
// an sType / pNext chain.
type Structure interface {
	GetType() StructureType
	toC() (unsafe.Pointer, func())
}

// _cGoString converts a null-terminated C string pointer to a Go string.
func _cGoString(ptr unsafe.Pointer) string {
	if ptr == nil {
		return ""
	}
	p := (*[1 << 30]byte)(ptr)
	for i, b := range p {
		if b == 0 {
			return string(p[:i])
		}
	}
	return ""
}

// _vkLib is the handle to the loaded Vulkan shared library.
var _vkLib unsafe.Pointer

// _vkGetInstanceProcAddr is the loaded vkGetInstanceProcAddr function pointer.
var _vkGetInstanceProcAddr unsafe.Pointer

// _vkGetDeviceProcAddr is the cached vkGetDeviceProcAddr, set by _initInstanceTable.
var _vkGetDeviceProcAddr unsafe.Pointer

// _loadProc loads a Vulkan function via vkGetInstanceProcAddr.
// instance may be nil for global-level functions.
func _loadProc(instance unsafe.Pointer, name string) unsafe.Pointer {
	nameBytes := append([]byte(name), 0)
	var pin runtime.Pinner
	pin.Pin(&nameBytes[0])
	defer pin.Unpin()
	namePtr := unsafe.Pointer(&nameBytes[0])
	var result unsafe.Pointer
	ffi.CallFunction(&_cif_vkGetInstanceProcAddr, _vkGetInstanceProcAddr, //nolint
		unsafe.Pointer(&result),
		[]unsafe.Pointer{unsafe.Pointer(&instance), unsafe.Pointer(&namePtr)},
	)
	return result
}

// _loadDeviceProc loads a Vulkan function via vkGetDeviceProcAddr.
func _loadDeviceProc(device unsafe.Pointer, name string) unsafe.Pointer {
	return _loadDeviceProcVia(_vkGetDeviceProcAddr, device, name)
}

func _loadDeviceProcVia(getDeviceProcAddrFn unsafe.Pointer, device unsafe.Pointer, name string) unsafe.Pointer {
	nameBytes := append([]byte(name), 0)
	var pin runtime.Pinner
	pin.Pin(&nameBytes[0])
	defer pin.Unpin()
	namePtr := unsafe.Pointer(&nameBytes[0])
	var result unsafe.Pointer
	ffi.CallFunction(&_cif_vkGetDeviceProcAddr, getDeviceProcAddrFn, //nolint
		unsafe.Pointer(&result),
		[]unsafe.Pointer{unsafe.Pointer(&device), unsafe.Pointer(&namePtr)},
	)
	return result
}

// _vulkanLibName returns the platform-specific Vulkan shared library name.
func _vulkanLibName() string {
	switch runtime.GOOS {
	case "windows":
		return "vulkan-1.dll"
	case "darwin":
		return "/opt/homebrew/lib/libvulkan.1.dylib"
	default:
		return "libvulkan.so.1"
	}
}

// SurfaceKHRFromHandle wraps a raw VkSurfaceKHR handle value into a
// *SurfaceKHR. Use this when you have the actual handle value (e.g. from
// platform-specific surface creation).
func SurfaceKHRFromHandle(handle uintptr) *SurfaceKHR {
	return &SurfaceKHR{handle: *(*unsafe.Pointer)(unsafe.Pointer(&handle))}
}

// SurfaceKHRFromGLFW wraps the uintptr returned by go-gl/glfw's
// Window.CreateWindowSurface into a *SurfaceKHR. GLFW returns a pointer to
// the VkSurfaceKHR, so this function dereferences it to get the actual handle.
// Must be called immediately after CreateWindowSurface in the same goroutine.
//
// Usage with go-gl/glfw:
//
//	surfPtr, err := window.CreateWindowSurface((*byte)(instance.Handle()), nil)
//	surface := vk.SurfaceKHRFromGLFW(surfPtr)
func SurfaceKHRFromGLFW(glfwSurface uintptr) *SurfaceKHR {
	ptr := *(*unsafe.Pointer)(unsafe.Pointer(&glfwSurface))
	handle := *(*uintptr)(ptr)
	return &SurfaceKHR{handle: *(*unsafe.Pointer)(unsafe.Pointer(&handle))}
}
`
