// This file has been generated by
// go-Vulkan please do not edit.

package vulkan

func PFN_vkInternalAllocationNotification (
	pUserData unsafe.Pointer,
	size uint,
	allocationType VkInternalAllocationType,
	allocationScope VkSystemAllocationScope,
)  {
}

func PFN_vkInternalFreeNotification (
	pUserData unsafe.Pointer,
	size uint,
	allocationType VkInternalAllocationType,
	allocationScope VkSystemAllocationScope,
)  {
}

func PFN_vkReallocationFunction (
	pUserData unsafe.Pointer,
	pOriginal unsafe.Pointer,
	size uint,
	alignment uint,
	allocationScope VkSystemAllocationScope,
) unsafe.Pointer {
}

func PFN_vkAllocationFunction (
	pUserData unsafe.Pointer,
	size uint,
	alignment uint,
	allocationScope VkSystemAllocationScope,
) unsafe.Pointer {
}

func PFN_vkFreeFunction (
	pUserData unsafe.Pointer,
	pMemory unsafe.Pointer,
)  {
}

func PFN_vkVoidFunction (
)  {
}

func PFN_vkDebugReportCallbackEXT (
	flags VkDebugReportFlagsEXT,
	objectType VkDebugReportObjectTypeEXT,
	object uint64,
	location uint,
	messageCode int32,
	pLayerPrefix *const char,
	pMessage *const char,
	pUserData unsafe.Pointer,
) VkBool32 {
}

func PFN_vkDebugUtilsMessengerCallbackEXT (
	messageSeverity VkDebugUtilsMessageSeverityFlagBitsEXT,
	messageTypes VkDebugUtilsMessageTypeFlagsEXT,
	pCallbackData *const VkDebugUtilsMessengerCallbackDataEXT,
	pUserData unsafe.Pointer,
) VkBool32 {
}

func PFN_vkFaultCallbackFunction (
	unrecordedFaults VkBool32,
	faultCount uint32,
	pFaults *const VkFaultData,
)  {
}

func PFN_vkDeviceMemoryReportCallbackEXT (
	pCallbackData *const VkDeviceMemoryReportCallbackDataEXT,
	pUserData unsafe.Pointer,
)  {
}

func PFN_vkGetInstanceProcAddrLUNARG (
	instance VkInstance,
	pName *const char,
) PFN_vkVoidFunction {
}

