// Code generated by vulkan-go generator. DO NOT EDIT.

//go:build linux

package vk

import (
	"unsafe"

	"github.com/go-webgpu/goffi/ffi"
)

type cVkWaylandSurfaceCreateInfoKHR struct {
	sType   int32
	pNext   unsafe.Pointer
	flags   uint32
	display unsafe.Pointer
	surface unsafe.Pointer
}

type WaylandSurfaceCreateInfoKHR struct {
	Next    Structure
	Flags   WaylandSurfaceCreateFlagsKHR
	Display unsafe.Pointer
	Surface unsafe.Pointer
}

func (s *WaylandSurfaceCreateInfoKHR) GetType() StructureType {
	return StructureTypeWaylandSurfaceCreateInfoKHR
}

func (s *WaylandSurfaceCreateInfoKHR) toC() (unsafe.Pointer, func()) {
	cancels := make([]func(), 0)
	p := new(cVkWaylandSurfaceCreateInfoKHR)
	p.sType = int32(s.GetType())
	if s.Next != nil {
		nextPtr, nextCancel := s.Next.toC()
		cancels = append(cancels, nextCancel)
		p.pNext = nextPtr
	}
	val0 := uint32(s.Flags)
	p.flags = val0
	ext1 := unsafe.Pointer(s.Display)
	p.display = ext1
	ext2 := unsafe.Pointer(s.Surface)
	p.surface = ext2
	return unsafe.Pointer(p), func() {
		for _, cancel := range cancels {
			cancel()
		}
	}
}

func (s *WaylandSurfaceCreateInfoKHR) fromC(p *cVkWaylandSurfaceCreateInfoKHR) {
	s.Flags = WaylandSurfaceCreateFlagsKHR(p.flags)
	s.Display = unsafe.Pointer(p.display)
	s.Surface = unsafe.Pointer(p.surface)
}

type cVkXcbSurfaceCreateInfoKHR struct {
	sType      int32
	pNext      unsafe.Pointer
	flags      uint32
	connection unsafe.Pointer
	window     uint32
}

type XcbSurfaceCreateInfoKHR struct {
	Next       Structure
	Flags      XcbSurfaceCreateFlagsKHR
	Connection unsafe.Pointer
	Window     uint32
}

func (s *XcbSurfaceCreateInfoKHR) GetType() StructureType {
	return StructureTypeXcbSurfaceCreateInfoKHR
}

func (s *XcbSurfaceCreateInfoKHR) toC() (unsafe.Pointer, func()) {
	cancels := make([]func(), 0)
	p := new(cVkXcbSurfaceCreateInfoKHR)
	p.sType = int32(s.GetType())
	if s.Next != nil {
		nextPtr, nextCancel := s.Next.toC()
		cancels = append(cancels, nextCancel)
		p.pNext = nextPtr
	}
	val0 := uint32(s.Flags)
	p.flags = val0
	ext1 := unsafe.Pointer(s.Connection)
	p.connection = ext1
	ext2 := uint32(s.Window)
	p.window = ext2
	return unsafe.Pointer(p), func() {
		for _, cancel := range cancels {
			cancel()
		}
	}
}

func (s *XcbSurfaceCreateInfoKHR) fromC(p *cVkXcbSurfaceCreateInfoKHR) {
	s.Flags = XcbSurfaceCreateFlagsKHR(p.flags)
	s.Connection = unsafe.Pointer(p.connection)
	s.Window = uint32(p.window)
}

type cVkXlibSurfaceCreateInfoKHR struct {
	sType  int32
	pNext  unsafe.Pointer
	flags  uint32
	dpy    unsafe.Pointer
	window uintptr
}

type XlibSurfaceCreateInfoKHR struct {
	Next   Structure
	Flags  XlibSurfaceCreateFlagsKHR
	Dpy    unsafe.Pointer
	Window uintptr
}

func (s *XlibSurfaceCreateInfoKHR) GetType() StructureType {
	return StructureTypeXlibSurfaceCreateInfoKHR
}

func (s *XlibSurfaceCreateInfoKHR) toC() (unsafe.Pointer, func()) {
	cancels := make([]func(), 0)
	p := new(cVkXlibSurfaceCreateInfoKHR)
	p.sType = int32(s.GetType())
	if s.Next != nil {
		nextPtr, nextCancel := s.Next.toC()
		cancels = append(cancels, nextCancel)
		p.pNext = nextPtr
	}
	val0 := uint32(s.Flags)
	p.flags = val0
	ext1 := unsafe.Pointer(s.Dpy)
	p.dpy = ext1
	ext2 := uintptr(s.Window)
	p.window = ext2
	return unsafe.Pointer(p), func() {
		for _, cancel := range cancels {
			cancel()
		}
	}
}

func (s *XlibSurfaceCreateInfoKHR) fromC(p *cVkXlibSurfaceCreateInfoKHR) {
	s.Flags = XlibSurfaceCreateFlagsKHR(p.flags)
	s.Dpy = unsafe.Pointer(p.dpy)
	s.Window = uintptr(p.window)
}

func (h Instance) CreateWaylandSurfaceKHR(
	CreateInfo *WaylandSurfaceCreateInfoKHR,
	Allocator *AllocationCallbacks,
) (*SurfaceKHR, error) {
	cancels := make([]func(), 0)
	defer func() {
		for _, c := range cancels {
			c()
		}
	}()

	_recv := h.handle
	var ptr0 unsafe.Pointer
	if CreateInfo != nil {
		val1, cancel2 := CreateInfo.toC()
		cancels = append(cancels, cancel2)
		ptr0 = val1
	}
	var ptr3 unsafe.Pointer
	if Allocator != nil {
		val4, cancel5 := Allocator.toC()
		cancels = append(cancels, cancel5)
		ptr3 = val4
	}
	var surfaceOut unsafe.Pointer
	_surfaceOutSlot := unsafe.Pointer(&surfaceOut)
	var _ret int32
	ffi.CallFunction(&_cif_vkCreateWaylandSurfaceKHR, h.table.vkCreateWaylandSurfaceKHR, unsafe.Pointer(&_ret), []unsafe.Pointer{
		unsafe.Pointer(&_recv),
		unsafe.Pointer(&ptr0),
		unsafe.Pointer(&ptr3),
		unsafe.Pointer(&_surfaceOutSlot),
	})
	if _ret != int32(Success) {
		return nil, Result(_ret)
	}
	h6 := &SurfaceKHR{handle: unsafe.Pointer(surfaceOut)}
	return h6, nil
}

func (h Instance) CreateXcbSurfaceKHR(
	CreateInfo *XcbSurfaceCreateInfoKHR,
	Allocator *AllocationCallbacks,
) (*SurfaceKHR, error) {
	cancels := make([]func(), 0)
	defer func() {
		for _, c := range cancels {
			c()
		}
	}()

	_recv := h.handle
	var ptr0 unsafe.Pointer
	if CreateInfo != nil {
		val1, cancel2 := CreateInfo.toC()
		cancels = append(cancels, cancel2)
		ptr0 = val1
	}
	var ptr3 unsafe.Pointer
	if Allocator != nil {
		val4, cancel5 := Allocator.toC()
		cancels = append(cancels, cancel5)
		ptr3 = val4
	}
	var surfaceOut unsafe.Pointer
	_surfaceOutSlot := unsafe.Pointer(&surfaceOut)
	var _ret int32
	ffi.CallFunction(&_cif_vkCreateXcbSurfaceKHR, h.table.vkCreateXcbSurfaceKHR, unsafe.Pointer(&_ret), []unsafe.Pointer{
		unsafe.Pointer(&_recv),
		unsafe.Pointer(&ptr0),
		unsafe.Pointer(&ptr3),
		unsafe.Pointer(&_surfaceOutSlot),
	})
	if _ret != int32(Success) {
		return nil, Result(_ret)
	}
	h6 := &SurfaceKHR{handle: unsafe.Pointer(surfaceOut)}
	return h6, nil
}

func (h Instance) CreateXlibSurfaceKHR(
	CreateInfo *XlibSurfaceCreateInfoKHR,
	Allocator *AllocationCallbacks,
) (*SurfaceKHR, error) {
	cancels := make([]func(), 0)
	defer func() {
		for _, c := range cancels {
			c()
		}
	}()

	_recv := h.handle
	var ptr0 unsafe.Pointer
	if CreateInfo != nil {
		val1, cancel2 := CreateInfo.toC()
		cancels = append(cancels, cancel2)
		ptr0 = val1
	}
	var ptr3 unsafe.Pointer
	if Allocator != nil {
		val4, cancel5 := Allocator.toC()
		cancels = append(cancels, cancel5)
		ptr3 = val4
	}
	var surfaceOut unsafe.Pointer
	_surfaceOutSlot := unsafe.Pointer(&surfaceOut)
	var _ret int32
	ffi.CallFunction(&_cif_vkCreateXlibSurfaceKHR, h.table.vkCreateXlibSurfaceKHR, unsafe.Pointer(&_ret), []unsafe.Pointer{
		unsafe.Pointer(&_recv),
		unsafe.Pointer(&ptr0),
		unsafe.Pointer(&ptr3),
		unsafe.Pointer(&_surfaceOutSlot),
	})
	if _ret != int32(Success) {
		return nil, Result(_ret)
	}
	h6 := &SurfaceKHR{handle: unsafe.Pointer(surfaceOut)}
	return h6, nil
}

func (h PhysicalDevice) GetWaylandPresentationSupportKHR(
	queueFamilyIndex uint32,
	display unsafe.Pointer,
) bool {
	cancels := make([]func(), 0)
	defer func() {
		for _, c := range cancels {
			c()
		}
	}()

	_recv := h.handle
	val0 := uint32(queueFamilyIndex)
	ext1 := unsafe.Pointer(display)
	var _ret uint32
	ffi.CallFunction(&_cif_vkGetPhysicalDeviceWaylandPresentationSupportKHR, h.table.vkGetPhysicalDeviceWaylandPresentationSupportKHR, unsafe.Pointer(&_ret), []unsafe.Pointer{
		unsafe.Pointer(&_recv),
		unsafe.Pointer(&val0),
		unsafe.Pointer(&ext1),
	})
	val2 := _ret != 0
	return val2
}

func (h PhysicalDevice) GetXcbPresentationSupportKHR(
	queueFamilyIndex uint32,
	connection unsafe.Pointer,
	visual_id uint32,
) bool {
	cancels := make([]func(), 0)
	defer func() {
		for _, c := range cancels {
			c()
		}
	}()

	_recv := h.handle
	val0 := uint32(queueFamilyIndex)
	ext1 := unsafe.Pointer(connection)
	ext2 := uint32(visual_id)
	var _ret uint32
	ffi.CallFunction(&_cif_vkGetPhysicalDeviceXcbPresentationSupportKHR, h.table.vkGetPhysicalDeviceXcbPresentationSupportKHR, unsafe.Pointer(&_ret), []unsafe.Pointer{
		unsafe.Pointer(&_recv),
		unsafe.Pointer(&val0),
		unsafe.Pointer(&ext1),
		unsafe.Pointer(&ext2),
	})
	val3 := _ret != 0
	return val3
}

func (h PhysicalDevice) GetXlibPresentationSupportKHR(
	queueFamilyIndex uint32,
	dpy unsafe.Pointer,
	visualID uintptr,
) bool {
	cancels := make([]func(), 0)
	defer func() {
		for _, c := range cancels {
			c()
		}
	}()

	_recv := h.handle
	val0 := uint32(queueFamilyIndex)
	ext1 := unsafe.Pointer(dpy)
	ext2 := uintptr(visualID)
	var _ret uint32
	ffi.CallFunction(&_cif_vkGetPhysicalDeviceXlibPresentationSupportKHR, h.table.vkGetPhysicalDeviceXlibPresentationSupportKHR, unsafe.Pointer(&_ret), []unsafe.Pointer{
		unsafe.Pointer(&_recv),
		unsafe.Pointer(&val0),
		unsafe.Pointer(&ext1),
		unsafe.Pointer(&ext2),
	})
	val3 := _ret != 0
	return val3
}
